
model:
    optimizer: 'Adam'
    scheduler: 'CosAn'
    loss: 'L2'    
    augmentation: True
    image_grad: False
    kernel_K: False
    pure_registration: False
    reduced_dim: 16
    pretrain_epoch: 300

solver:
    lr: 0.0005
    epochs: 1000
    batch_size: 4
    weight_decay: 0.0001
    Euler_steps: 10
    Alpha: 2.0 
    Gamma: 1.0
    Lpow: 4  
    Sigma: 0.02