
model:
    optimizer: 'Adam'
    scheduler: 'CosAn'
    loss: 'L2'    
    augmentation: True
    image_grad: False
    kernel_K: False
    pure_atlas_bulding: True
    reduced_dim: 16
    pretrain_epoch: 300

solver:
    lr: 0.001
    epochs: 3
    batch_size: 1
    weight_decay: 0.0001
    pre_train: 1
    Euler_steps: 10
    Alpha: 2.0 
    Gamma: 1.0
    Lpow: 4  
    Sigma: 0.02